version: '3'
services:
  mysql:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: ./web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/myapp
      - gem_data:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    stdin_open: true
    tty: true

volumes:
  mysql-data:
  gem_data:
    driver: local